language: java
jdk: oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: "86ba0a4e-7d26-4cb0-b2d4-8198358b3279"

addons:
  sonarqube:
    token:
      secure: c9495ad0cde57c7a52fa10eb7c19c0ae62853876 # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar