language: java
jdk: oraclejdk8

env:
  global:
    - SAUCE_USERNAME="nephology"
    - secure: "44HtPJQunhxmIxn3e68jBjZRwpHHlPywiK136CGYWka6cyPGWC+sXZXjpOU5MfT5EfJqH
                       ij4F5B2jMrF/Msda9E5hcDbpT+q6SmB049aYst9oZDtOGD/hQF2TFkSiaFkrxU+JBeTFoZwHhF7N4uOM
                       2Uj9nT4KzDtKvft89l8+mRxf/93BAypFwBJfe0qWf9QSzV4DI82KwMCy27gv8NNBg9Al6SjNcChsowDq
                       +P8+A+O/nlPsOAOalzi8uNblakaeZd2Y+16vH6RucNS1fXbRbJnOzavNUOzaytzds/UnsqLjEJv/Qk1w
                       4F2v+wfKM2cAortsn74WAeILlzeS2ZCmLkV+9uuDkMTSOQd4U59btLyHaOH/glMos9ylOcXq679fIx3f
                       fO61dk3dGMoXkZwWj/KGUlmyRtjP66u1avFYpeNn0aYkTiW9Pz5Uqzje9HgVr+ToFDsxOj0gQMmnlR6M
                       0WwDcdhRuzbinXa96/KIHIU/JYv+zAqdZbCd8XITWF5gpWxiU19glyxkK+ypKCagyMgsp+YwTIdmGhB7
                       OXwl3W1SDVFyB3T94Cv2sp0DSVaQPybCfTgc+fphPtm+g8bHRoRZp4amfgr5XP7iiTyoGmtcok+AiDI3
                       6iJoX1zXZ4fYxd9cNbj+aCYWK0L+tKz+oLg1P0Y1UNvsDZIliH8VVs="

deploy:
  provider: heroku
  api_key:
    secure: "86ba0a4e-7d26-4cb0-b2d4-8198358b3279"

addons:
  sauce_connect: true

sonarqube:
  token:
    secure: c9495ad0cde57c7a52fa10eb7c19c0ae62853876 # encrypted value of your token
  branches:
    - master

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
